### ISSUE TITLE
Namechanged players can't vote for essence

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/EssenceGlue#1]
Need to get account based on current mojang name if initial lookup returns no valid player

**Comment by KaloHG** [comment]
This took a while to setup. 

What if instead of having EssenceGlue use the vote.getUsername in order to identify the player. It instead used vote.getAddress (IP Address), and have it identify players via that? I feel like that would be a pretty simple fix since the framework is already there. 

Only issue I see with this is the fact that when using player.getAddress (Bukkit) through a bungeecoord proxy, it could potentially return 127.0.0.1 (localhost.)

**Comment by Maxopoly** [comment]
IP adresses do not uniquely identify players, there are quite a few players playing on the same IP who have manual alt groups set via BanStick. Just a raw IP could not be tied to either of them. We need to instead lookup the name history via Mojangs API.

**Comment by KaloHG** [comment]
Only problem I can really find with that is the possibility of potentially having it try to give Essence to the wrong player due to a past name. I don't really know how you would go about pulling old usernames from the Mojang API so I don't think I can be much of a help here. Sorry.

**Comment by crimsonblod** [comment]
Could this site here be of help in that?

https://wiki.vg/Mojang_API#UUID_-.3E_Name_history

```
  GET https://api.mojang.com/user/profiles/<uuid>/names
Returns all the usernames this user has used in the past and the one they are using currently. The UUID must be given without hyphens.

Response
[
  {
    "name": "Gold"
  },
  {
    "name": "Diamond",
    "changedToAt": 1414059749000
  }
]
The changedToAt field is a Java timestamp in milliseconds.
```

**Comment by Maxopoly** [comment]
Should be fixed by https://github.com/CivClassic/EssenceGlue/commit/2656c1425747635a0d6890991bc30b4bb593bb01

Name changed players should use their current mojang name and be online at the time of voting.
